[package]
name = "nss-resolver"
version = "0.1.0"
authors = ["Sonny Scroggin <sonny@scrogg.in>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
nsswitch_service = {git = "https://github.com/jorendorff/nsswitch_service"}
